version: "3"

services:
  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./volumes/user_db:/user_db
    environment:
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: user_db_pass
      POSTGRES_DB: user_db
      PGDATA: /user_db

  redis:
    image: redis:5-alpine
    volumes:
      - ./volumes/redis:/data

  api:
    image: avatsaev/angular-contacts-api:dev
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    environment:
      SERVER_PORT: 3000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: user_db_pass
      POSTGRES_DB: user_db
      REDIS_HOST: redis
      REDIS_PORT: 6379

  client:
    build:
      context: .
      args:
        NG_ENV: local
    restart: always
    ports:
      - 4000:80
